// This file was generated by liblab | https://liblab.com/

using NhlClient;
using NhlClient.Config;
using Environment = NhlClient.Http.Environment;

var config = new NhlClientConfig { Environment = Environment.Default };

var client = new NhlClientClient(config);

var response = await client.SkaterStats.GetCurrentSkaterStatsLeadersAsync("categories", 3);

Console.WriteLine(response);
